services:
  directory-service:
    container_name: directory-service
    build:
      context: .
      dockerfile: /backend/DirectoryService/DirectoryService.Web/Dockerfile
      secrets:
        - nuget_config
        - nuget_username
        - nuget_password
    ports:
      - "9002:8080"
    env_file:
      - DirectoryService.Development.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      postgres:
        condition: service_healthy
      seq:
        condition: service_started
      loki:
        condition: service_started
    restart: unless-stopped

  seq:
    container_name: directory-service-seq
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_NOAUTHENTICATION: "true"
    ports:
      - "15341:5341"
      - "8081:80"
    restart: always

  postgres:
    container_name: directory-service-postgres
    image: postgres:15
    env_file:
      - DirectoryService.Development.env
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgresUser -d directory_service" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always

  minio:
    container_name: file-service-minio
    image: minio/minio:latest
    env_file:
      - FileService.Development.env
    ports:
      - "19000:9000"
      - "19001:9001"
    command: server /data --console-address ":9001"
    restart: always

  file-service:
    container_name: file-service
    build:
      context: .
      dockerfile: /backend/FileService/FileService.Web/Dockerfile
      secrets:
        - nuget_config
        - nuget_username
        - nuget_password
    ports:
      - "8002:8080"
    env_file:
      - FileService.Development.env
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      ASPNETCORE_URLS: http://+:8080
    depends_on:
      - postgres
      - redis
      - seq
      - loki
    tty: true
    stdin_open: true
    restart: unless-stopped

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - DirectoryService.Development.env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - loki

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:

secrets:
  nuget_config:
    file: ./nuget.config
  nuget_username:
    environment: NUGET_USERNAME
  nuget_password:
    environment: NUGET_PASSWORD