<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>IstredDev.FileService.Contracts</PackageId>
    <Version>0.2.0</Version>
    <Authors>Istred</Authors>
    <Company>Istred</Company>
    <PackageDescription>Framework</PackageDescription>
    <RepositoryUrl>https://gitlab.com/yudjineist/directory-service</RepositoryUrl>
  </PropertyGroup>
  <ItemGroup>
    <Protobuf Include="Grpc\Protos\file_internal.proto" GrpcServices="Both" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Grpc.Core.Api" />
    <PackageReference Include="Grpc.Net.ClientFactory" />
    <PackageReference Include="Grpc.Tools" PrivateAssets="all" />
    <PackageReference Include="istreddev.framework" />
    <PackageReference Include="istreddev.sharedkernel" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="WolverineFx.EntityFrameworkCore" />
    <PackageReference Include="WolverineFx.Postgresql" />
    <PackageReference Include="WolverineFx.RabbitMQ" />
  </ItemGroup>
</Project>
