// <auto-generated />
using System;
using AuthService.Infrastructure.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AuthService.Infrastructure.Postgres.Migrations
{
    [DbContext(typeof(AuthServiceDbContext))]
    partial class AuthServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AuthService.Domain.Users.AuthUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("timezone('utc',now())");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("timezone('utc',now())");

                    b.HasKey("Id");

                    b.ToTable("auth_users", (string)null);
                });

            modelBuilder.Entity("AuthService.Domain.Users.AuthUser", b =>
                {
                    b.OwnsOne("AuthService.Domain.Users.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("AuthUserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(320)
                                .HasColumnType("character varying(320)")
                                .HasColumnName("email");

                            b1.HasKey("AuthUserId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("ix_auth_users_email");

                            b1.ToTable("auth_users");

                            b1.WithOwner()
                                .HasForeignKey("AuthUserId");
                        });

                    b.OwnsOne("AuthService.Domain.Users.PasswordHash", "PasswordHash", b1 =>
                        {
                            b1.Property<Guid>("AuthUserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("password_hash");

                            b1.HasKey("AuthUserId");

                            b1.ToTable("auth_users");

                            b1.WithOwner()
                                .HasForeignKey("AuthUserId");
                        });

                    b.OwnsOne("AuthService.Domain.Users.Username", "Username", b1 =>
                        {
                            b1.Property<Guid>("AuthUserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("username");

                            b1.HasKey("AuthUserId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("ix_auth_users_username");

                            b1.ToTable("auth_users");

                            b1.WithOwner()
                                .HasForeignKey("AuthUserId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("PasswordHash")
                        .IsRequired();

                    b.Navigation("Username")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
